drop table if exists public.brands CASCADE;

create table brands
(
    brand_id   BIGINT generated by default as identity,
    brand_name TEXT not null,
    brand_status TEXT not null,
    primary key (brand_id)
);